# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/cocoapods/specs.git'

target 'FWCycleScrollView' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # 图片加载缓存：https://github.com/onevcat/Kingfisher
    pod 'Kingfisher'
    
end
