# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FWCycleScrollView' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # 图片加载缓存：https://github.com/onevcat/Kingfisher
    pod 'Kingfisher'
    
end
